"""Type stubs for ranklab Python bindings."""

from typing import Dict, List, Optional, Tuple

# Differentiable ranking

def soft_rank(scores: List[float], temperature: float = 1.0) -> List[float]: ...
def soft_rank_neural_sort(scores: List[float], temperature: float = 1.0) -> List[float]: ...
def soft_rank_sigmoid(scores: List[float], temperature: float = 1.0) -> List[float]: ...
def soft_rank_smooth_i(scores: List[float], temperature: float = 1.0) -> List[float]: ...
def differentiable_topk(scores: List[float], k: int, temperature: float = 1.0) -> Tuple[List[float], List[float]]: ...

# LTR losses

def ranknet_loss(predictions: List[float], relevance: List[float]) -> float: ...
def approx_ndcg(predictions: List[float], relevance: List[float], temperature: float = 1.0, k: Optional[int] = None) -> float: ...
def lambda_loss(predictions: List[float], relevance: List[float], k: Optional[int] = None) -> float: ...
def listnet_loss(predictions: List[float], relevance: List[float], temperature: float = 1.0) -> float: ...
def listmle_loss(predictions: List[float], relevance: List[float], temperature: float = 1.0) -> float: ...

# Gradient computation

def compute_lambdarank_gradients(scores: List[float], relevance: List[float], k: Optional[int] = None, sigma: float = 1.0, cost_sensitive: bool = False) -> List[float]: ...
def compute_ranking_svm_gradients(scores: List[float], relevance: List[float], c: float = 1.0, normalize_queries: bool = False) -> List[float]: ...

# Eval metrics

def ndcg(ranked: List[Tuple[str, float]], qrels: Dict[str, int], k: int) -> float: ...
def map_score(ranked: List[Tuple[str, float]], qrels: Dict[str, int]) -> float: ...
def mrr(ranked: List[Tuple[str, float]], qrels: Dict[str, int]) -> float: ...
def precision_at_k(ranked: List[Tuple[str, float]], qrels: Dict[str, int], k: int) -> float: ...
def recall_at_k(ranked: List[Tuple[str, float]], qrels: Dict[str, int], k: int) -> float: ...
